apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-server.fullname" . }}
  labels:
    app: {{ include "web-server.name" . }}
spec:
  selector:
    app: {{ include "web-server.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
